export interface FieldSchema {
  id: string; 
  label: string; 
  type: 'text' | 'email' | 'number' | 'url' | 'date' | 'select' | 'file';
  regex: RegExp;
  options?: string[];
}

export interface SectionSchema {
  id: string; 
  title: string;
  icon: string;
  isArray?: boolean; 
  fields: FieldSchema[];
}

const schemaSections: SectionSchema[] = [
  {
    id: 'personalInformation',
    title: 'Personal Information',
    icon: 'CheckCircle2',
    fields: [
      { id: 'fullName', label: 'Full Name', type: 'text', regex: /full.*name/i },
      { id: 'firstName', label: 'First Name', type: 'text', regex: /first.*name/i },
      { id: 'middleName', label: 'Middle Name', type: 'text', regex: /middle.*name/i },
      { id: 'lastName', label: 'Last Name', type: 'text', regex: /last.*name/i },
      { id: 'nameAsPerAadhaar', label: 'Name as per Aadhaar', type: 'text', regex: /name.*as.*per.*aadhaar/i },
      { id: 'nameAsPerPan', label: 'Name as per PAN', type: 'text', regex: /name.*as.*per.*pan/i },
      { id: 'preferredName', label: 'Preferred Name', type: 'text', regex: /preferred.*name/i },
      { id: 'fathersName', label: 'Fathers Name', type: 'text', regex: /fathers.*name/i },
      { id: 'mothersName', label: 'Mothers Name', type: 'text', regex: /mothers.*name/i },
      { id: 'guardianName', label: 'Guardian Name', type: 'text', regex: /guardian.*name/i },
      { id: 'dateOfBirth', label: 'Date of Birth', type: 'text', regex: /date.*of.*birth/i },
      { id: 'age', label: 'Age', type: 'text', regex: /age/i },
      { id: 'gender', label: 'Gender', type: 'text', regex: /gender/i },
      { id: 'maritalStatus', label: 'Marital Status', type: 'text', regex: /marital.*status/i },
      { id: 'nationality', label: 'Nationality', type: 'text', regex: /nationality/i },
      { id: 'citizenship', label: 'Citizenship', type: 'text', regex: /citizenship/i },
      { id: 'ociStatus', label: 'OCI Status', type: 'text', regex: /oci.*status/i },
      { id: 'passportNumber', label: 'Passport Number', type: 'text', regex: /passport.*number/i },
      { id: 'aadhaarNumber', label: 'Aadhaar Number', type: 'text', regex: /aadhaar.*number/i },
      { id: 'panNumber', label: 'PAN Number', type: 'text', regex: /pan.*number/i },
      { id: 'photograph', label: 'Photograph', type: 'text', regex: /photograph/i },
      { id: 'signature', label: 'Signature', type: 'text', regex: /signature/i },
    ]
  },
  {
    id: 'contactDetails',
    title: 'Contact Details',
    icon: 'CheckCircle2',
    fields: [
      { id: 'personalEmail', label: 'Personal Email', type: 'email', regex: /personal.*email/i },
      { id: 'collegeEmail', label: 'College Email', type: 'email', regex: /college.*email/i },
      { id: 'alternateEmail', label: 'Alternate Email', type: 'email', regex: /alternate.*email/i },
      { id: 'mobileNumber', label: 'Mobile Number', type: 'text', regex: /mobile.*number/i },
      { id: 'alternateMobileNumber', label: 'Alternate Mobile Number', type: 'text', regex: /alternate.*mobile.*number/i },
      { id: 'whatsappNumber', label: 'WhatsApp Number', type: 'text', regex: /whatsapp.*number/i },
      { id: 'emergencyContactName', label: 'Emergency Contact Name', type: 'text', regex: /emergency.*contact.*name/i },
      { id: 'emergencyContactNumber', label: 'Emergency Contact Number', type: 'text', regex: /emergency.*contact.*number/i },
      { id: 'emergencyContactRelationship', label: 'Emergency Contact Relationship', type: 'text', regex: /emergency.*contact.*relationship/i },
      { id: 'currentAddress', label: 'Current Address', type: 'text', regex: /current.*address/i },
      { id: 'permanentAddress', label: 'Permanent Address', type: 'text', regex: /permanent.*address/i },
      { id: 'addressLine1', label: 'Address Line 1', type: 'text', regex: /address.*line.*1/i },
      { id: 'addressLine2', label: 'Address Line 2', type: 'text', regex: /address.*line.*2/i },
      { id: 'city', label: 'City', type: 'text', regex: /city/i },
      { id: 'state', label: 'State', type: 'text', regex: /state/i },
      { id: 'country', label: 'Country', type: 'text', regex: /country/i },
      { id: 'pinCode', label: 'PIN Code', type: 'text', regex: /pin.*code/i },
      { id: 'currentCity', label: 'Current City', type: 'text', regex: /current.*city/i },
      { id: 'permanentCity', label: 'Permanent City', type: 'text', regex: /permanent.*city/i },
      { id: 'currentState', label: 'Current State', type: 'text', regex: /current.*state/i },
      { id: 'permanentState', label: 'Permanent State', type: 'text', regex: /permanent.*state/i },
    ]
  },
  {
    id: 'locationQuestions',
    title: 'Location Questions',
    icon: 'CheckCircle2',
    fields: [
      { id: 'whereDoYouCurrentlyLive', label: 'Where do you currently live', type: 'text', regex: /where.*do.*you.*currently.*live/i },
      { id: 'whatIsYourPermanentLocation', label: 'What is your permanent location', type: 'text', regex: /what.*is.*your.*permanent.*location/i },
      { id: 'areYouWillingToRelocate', label: 'Are you willing to relocate', type: 'text', regex: /are.*you.*willing.*to.*relocate/i },
      { id: 'preferredRelocationLocations', label: 'Preferred relocation locations', type: 'text', regex: /preferred.*relocation.*locations/i },
      { id: 'areYouWillingToRelocateAnywhereInIndia', label: 'Are you willing to relocate anywhere in India', type: 'text', regex: /are.*you.*willing.*to.*relocate.*anywhere.*in.*india/i },
      { id: 'areYouWillingToRelocateInternationally', label: 'Are you willing to relocate internationally', type: 'text', regex: /are.*you.*willing.*to.*relocate.*internationally/i },
      { id: 'preferredWorkLocation', label: 'Preferred work location', type: 'text', regex: /preferred.*work.*location/i },
      { id: 'preferredJobLocation', label: 'Preferred job location', type: 'text', regex: /preferred.*job.*location/i },
      { id: 'areYouWillingToWorkFromOffice', label: 'Are you willing to work from office', type: 'text', regex: /are.*you.*willing.*to.*work.*from.*office/i },
      { id: 'areYouWillingToWorkRemotely', label: 'Are you willing to work remotely', type: 'text', regex: /are.*you.*willing.*to.*work.*remotely/i },
      { id: 'areYouComfortableWithHybridWork', label: 'Are you comfortable with hybrid work', type: 'text', regex: /are.*you.*comfortable.*with.*hybrid.*work/i },
      { id: 'preferredWorkMode', label: 'Preferred work mode', type: 'text', regex: /preferred.*work.*mode/i },
      { id: 'areYouWillingToTravelForWork', label: 'Are you willing to travel for work', type: 'text', regex: /are.*you.*willing.*to.*travel.*for.*work/i },
      { id: 'areYouWillingToWorkAtAnotherCompanyLocation', label: 'Are you willing to work at another company location', type: 'text', regex: /are.*you.*willing.*to.*work.*at.*another.*company.*location/i },
    ]
  },
  {
    id: '10ThEducation',
    title: '10th Education',
    icon: 'CheckCircle2',
    fields: [
      { id: '10ThSchoolName', label: '10th School Name', type: 'text', regex: /10th.*school.*name/i },
      { id: '10ThBoard', label: '10th Board', type: 'text', regex: /10th.*board/i },
      { id: '10ThUniversityBoard', label: '10th University/Board', type: 'text', regex: /10th.*university.*board/i },
      { id: '10ThPassingYear', label: '10th Passing Year', type: 'text', regex: /10th.*passing.*year/i },
      { id: '10ThPercentage', label: '10th Percentage', type: 'text', regex: /10th.*percentage/i },
      { id: '10ThCgpa', label: '10th CGPA', type: 'text', regex: /10th.*cgpa/i },
      { id: '10ThGrade', label: '10th Grade', type: 'text', regex: /10th.*grade/i },
      { id: '10ThStream', label: '10th Stream', type: 'text', regex: /10th.*stream/i },
      { id: '10ThCity', label: '10th City', type: 'text', regex: /10th.*city/i },
      { id: '10ThState', label: '10th State', type: 'text', regex: /10th.*state/i },
      { id: '10ThCountry', label: '10th Country', type: 'text', regex: /10th.*country/i },
    ]
  },
  {
    id: '12ThEducation',
    title: '12th Education',
    icon: 'CheckCircle2',
    fields: [
      { id: '12ThSchoolName', label: '12th School Name', type: 'text', regex: /12th.*school.*name/i },
      { id: '12ThBoard', label: '12th Board', type: 'text', regex: /12th.*board/i },
      { id: '12ThPassingYear', label: '12th Passing Year', type: 'text', regex: /12th.*passing.*year/i },
      { id: '12ThPercentage', label: '12th Percentage', type: 'text', regex: /12th.*percentage/i },
      { id: '12ThCgpa', label: '12th CGPA', type: 'text', regex: /12th.*cgpa/i },
      { id: '12ThGrade', label: '12th Grade', type: 'text', regex: /12th.*grade/i },
      { id: '12ThStream', label: '12th Stream', type: 'text', regex: /12th.*stream/i },
      { id: '12ThCity', label: '12th City', type: 'text', regex: /12th.*city/i },
      { id: '12ThState', label: '12th State', type: 'text', regex: /12th.*state/i },
      { id: '12ThCountry', label: '12th Country', type: 'text', regex: /12th.*country/i },
    ]
  },
  {
    id: 'diploma',
    title: 'Diploma',
    icon: 'CheckCircle2',
    fields: [
      { id: 'diplomaCollege', label: 'Diploma College', type: 'text', regex: /diploma.*college/i },
      { id: 'diplomaCourse', label: 'Diploma Course', type: 'text', regex: /diploma.*course/i },
      { id: 'diplomaSpecialization', label: 'Diploma Specialization', type: 'text', regex: /diploma.*specialization/i },
      { id: 'diplomaUniversity', label: 'Diploma University', type: 'text', regex: /diploma.*university/i },
      { id: 'diplomaBoard', label: 'Diploma Board', type: 'text', regex: /diploma.*board/i },
      { id: 'diplomaStartYear', label: 'Diploma Start Year', type: 'text', regex: /diploma.*start.*year/i },
      { id: 'diplomaPassingYear', label: 'Diploma Passing Year', type: 'text', regex: /diploma.*passing.*year/i },
      { id: 'diplomaPercentage', label: 'Diploma Percentage', type: 'text', regex: /diploma.*percentage/i },
      { id: 'diplomaCgpa', label: 'Diploma CGPA', type: 'text', regex: /diploma.*cgpa/i },
      { id: 'diplomaCity', label: 'Diploma City', type: 'text', regex: /diploma.*city/i },
      { id: 'diplomaState', label: 'Diploma State', type: 'text', regex: /diploma.*state/i },
    ]
  },
  {
    id: 'undergraduateBTech',
    title: 'Undergraduate / B.Tech',
    icon: 'CheckCircle2',
    fields: [
      { id: 'collegeName', label: 'College Name', type: 'text', regex: /college.*name/i },
      { id: 'universityName', label: 'University Name', type: 'text', regex: /university.*name/i },
      { id: 'degree', label: 'Degree', type: 'text', regex: /degree/i },
      { id: 'course', label: 'Course', type: 'text', regex: /course/i },
      { id: 'branch', label: 'Branch', type: 'text', regex: /branch/i },
      { id: 'specialization', label: 'Specialization', type: 'text', regex: /specialization/i },
      { id: 'major', label: 'Major', type: 'text', regex: /major/i },
      { id: 'minor', label: 'Minor', type: 'text', regex: /minor/i },
      { id: 'btechStartYear', label: 'BTech Start Year', type: 'text', regex: /btech.*start.*year/i },
      { id: 'graduationYear', label: 'Graduation Year', type: 'text', regex: /graduation.*year/i },
      { id: 'expectedGraduationYear', label: 'Expected Graduation Year', type: 'text', regex: /expected.*graduation.*year/i },
      { id: 'currentYear', label: 'Current Year', type: 'text', regex: /current.*year/i },
      { id: 'currentSemester', label: 'Current Semester', type: 'text', regex: /current.*semester/i },
      { id: 'cgpa', label: 'CGPA', type: 'text', regex: /cgpa/i },
      { id: 'percentage', label: 'Percentage', type: 'text', regex: /percentage/i },
      { id: 'aggregatePercentage', label: 'Aggregate Percentage', type: 'text', regex: /aggregate.*percentage/i },
      { id: 'currentBacklogs', label: 'Current Backlogs', type: 'text', regex: /current.*backlogs/i },
      { id: 'activeBacklogs', label: 'Active Backlogs', type: 'text', regex: /active.*backlogs/i },
      { id: 'historyOfBacklogs', label: 'History of Backlogs', type: 'text', regex: /history.*of.*backlogs/i },
      { id: 'numberOfBacklogs', label: 'Number of Backlogs', type: 'text', regex: /number.*of.*backlogs/i },
      { id: 'numberOfAttempts', label: 'Number of Attempts', type: 'text', regex: /number.*of.*attempts/i },
      { id: 'gapInEducation', label: 'Gap in Education', type: 'text', regex: /gap.*in.*education/i },
      { id: 'gapDuration', label: 'Gap Duration', type: 'text', regex: /gap.*duration/i },
      { id: 'reasonForGap', label: 'Reason for Gap', type: 'text', regex: /reason.*for.*gap/i },
      { id: 'mediumOfInstruction', label: 'Medium of Instruction', type: 'text', regex: /medium.*of.*instruction/i },
      { id: 'collegeCity', label: 'College City', type: 'text', regex: /college.*city/i },
      { id: 'collegeState', label: 'College State', type: 'text', regex: /college.*state/i },
      { id: 'collegeCountry', label: 'College Country', type: 'text', regex: /college.*country/i },
    ]
  },
  {
    id: 'postgraduate',
    title: 'Postgraduate',
    icon: 'CheckCircle2',
    fields: [
      { id: 'pgCollege', label: 'PG College', type: 'text', regex: /pg.*college/i },
      { id: 'pgUniversity', label: 'PG University', type: 'text', regex: /pg.*university/i },
      { id: 'pgDegree', label: 'PG Degree', type: 'text', regex: /pg.*degree/i },
      { id: 'pgCourse', label: 'PG Course', type: 'text', regex: /pg.*course/i },
      { id: 'pgSpecialization', label: 'PG Specialization', type: 'text', regex: /pg.*specialization/i },
      { id: 'pgStartYear', label: 'PG Start Year', type: 'text', regex: /pg.*start.*year/i },
      { id: 'pgPassingYear', label: 'PG Passing Year', type: 'text', regex: /pg.*passing.*year/i },
      { id: 'pgCgpa', label: 'PG CGPA', type: 'text', regex: /pg.*cgpa/i },
      { id: 'pgPercentage', label: 'PG Percentage', type: 'text', regex: /pg.*percentage/i },
      { id: 'currentPgSemester', label: 'Current PG Semester', type: 'text', regex: /current.*pg.*semester/i },
    ]
  },
  {
    id: 'workExperience',
    title: 'Work Experience',
    icon: 'CheckCircle2',
    isArray: true,
    fields: [
      { id: 'doYouHaveWorkExperience', label: 'Do you have work experience', type: 'text', regex: /do.*you.*have.*work.*experience/i },
      { id: 'totalWorkExperience', label: 'Total Work Experience', type: 'text', regex: /total.*work.*experience/i },
      { id: 'yearsOfExperience', label: 'Years of Experience', type: 'text', regex: /years.*of.*experience/i },
      { id: 'monthsOfExperience', label: 'Months of Experience', type: 'text', regex: /months.*of.*experience/i },
      { id: 'previousCompany', label: 'Previous Company', type: 'text', regex: /previous.*company/i },
      { id: 'employerName', label: 'Employer Name', type: 'text', regex: /employer.*name/i },
      { id: 'jobTitle', label: 'Job Title', type: 'text', regex: /job.*title/i },
      { id: 'position', label: 'Position', type: 'text', regex: /position/i },
      { id: 'jobType', label: 'Job Type', type: 'text', regex: /job.*type/i },
      { id: 'employmentType', label: 'Employment Type', type: 'text', regex: /employment.*type/i },
      { id: 'fullTimePartTime', label: 'Full-time/Part-time', type: 'text', regex: /full.*time.*part.*time/i },
      { id: 'startDate', label: 'Start Date', type: 'text', regex: /start.*date/i },
      { id: 'endDate', label: 'End Date', type: 'text', regex: /end.*date/i },
      { id: 'currentEmployer', label: 'Current Employer', type: 'text', regex: /current.*employer/i },
      { id: 'currentJob', label: 'Current Job', type: 'text', regex: /current.*job/i },
      { id: 'city', label: 'City', type: 'text', regex: /city/i },
      { id: 'country', label: 'Country', type: 'text', regex: /country/i },
      { id: 'responsibilities', label: 'Responsibilities', type: 'text', regex: /responsibilities/i },
      { id: 'jobDescription', label: 'Job Description', type: 'text', regex: /job.*description/i },
      { id: 'reasonForLeaving', label: 'Reason for Leaving', type: 'text', regex: /reason.*for.*leaving/i },
      { id: 'previousSalary', label: 'Previous Salary', type: 'text', regex: /previous.*salary/i },
      { id: 'currentSalary', label: 'Current Salary', type: 'text', regex: /current.*salary/i },
      { id: 'currentCtc', label: 'Current CTC', type: 'text', regex: /current.*ctc/i },
      { id: 'noticePeriod', label: 'Notice Period', type: 'text', regex: /notice.*period/i },
      { id: 'lastWorkingDay', label: 'Last Working Day', type: 'text', regex: /last.*working.*day/i },
      { id: 'additionalWorkExperience', label: 'Additional Work Experience', type: 'text', regex: /additional.*work.*experience/i },
      { id: 'previousEmployer', label: 'Previous Employer', type: 'text', regex: /previous.*employer/i },
      { id: 'previousJobTitle', label: 'Previous Job Title', type: 'text', regex: /previous.*job.*title/i },
    ]
  },
  {
    id: 'internship',
    title: 'Internship',
    icon: 'CheckCircle2',
    isArray: true,
    fields: [
      { id: 'haveYouCompletedAnInternship', label: 'Have you completed an internship', type: 'text', regex: /have.*you.*completed.*an.*internship/i },
      { id: 'internshipCompany', label: 'Internship Company', type: 'text', regex: /internship.*company/i },
      { id: 'employer', label: 'Employer', type: 'text', regex: /employer/i },
      { id: 'internshipTitle', label: 'Internship Title', type: 'text', regex: /internship.*title/i },
      { id: 'position', label: 'Position', type: 'text', regex: /position/i },
      { id: 'internshipType', label: 'Internship Type', type: 'text', regex: /internship.*type/i },
      { id: 'internshipLocation', label: 'Internship Location', type: 'text', regex: /internship.*location/i },
      { id: 'city', label: 'City', type: 'text', regex: /city/i },
      { id: 'country', label: 'Country', type: 'text', regex: /country/i },
      { id: 'startDate', label: 'Start Date', type: 'text', regex: /start.*date/i },
      { id: 'endDate', label: 'End Date', type: 'text', regex: /end.*date/i },
      { id: 'duration', label: 'Duration', type: 'text', regex: /duration/i },
      { id: 'internshipResponsibilities', label: 'Internship Responsibilities', type: 'text', regex: /internship.*responsibilities/i },
      { id: 'internshipDescription', label: 'Internship Description', type: 'text', regex: /internship.*description/i },
      { id: 'technologiesUsed', label: 'Technologies Used', type: 'text', regex: /technologies.*used/i },
      { id: 'whatDidYouWorkOn', label: 'What did you work on', type: 'text', regex: /what.*did.*you.*work.*on/i },
      { id: 'internshipProject', label: 'Internship Project', type: 'text', regex: /internship.*project/i },
      { id: 'internshipCertificate', label: 'Internship Certificate', type: 'text', regex: /internship.*certificate/i },
      { id: 'certificateLink', label: 'Certificate Link', type: 'text', regex: /certificate.*link/i },
      { id: 'internshipStipend', label: 'Internship Stipend', type: 'text', regex: /internship.*stipend/i },
      { id: 'wasTheInternshipPaid', label: 'Was the internship paid', type: 'text', regex: /was.*the.*internship.*paid/i },
      { id: 'additionalInternshipExperience', label: 'Additional Internship Experience', type: 'text', regex: /additional.*internship.*experience/i },
    ]
  },
  {
    id: 'technicalSkills',
    title: 'Technical Skills',
    icon: 'CheckCircle2',
    fields: [
      { id: 'programmingLanguages', label: 'Programming Languages', type: 'text', regex: /programming.*languages/i },
      { id: 'c', label: 'C', type: 'text', regex: /c/i },
      { id: 'java', label: 'Java', type: 'text', regex: /java/i },
      { id: 'python', label: 'Python', type: 'text', regex: /python/i },
      { id: 'javascript', label: 'JavaScript', type: 'text', regex: /javascript/i },
      { id: 'typescript', label: 'TypeScript', type: 'text', regex: /typescript/i },
      { id: 'sql', label: 'SQL', type: 'text', regex: /sql/i },
      { id: 'html', label: 'HTML', type: 'text', regex: /html/i },
      { id: 'css', label: 'CSS', type: 'text', regex: /css/i },
      { id: 'frontendTechnologies', label: 'Frontend Technologies', type: 'text', regex: /frontend.*technologies/i },
      { id: 'backendTechnologies', label: 'Backend Technologies', type: 'text', regex: /backend.*technologies/i },
      { id: 'frameworks', label: 'Frameworks', type: 'text', regex: /frameworks/i },
      { id: 'libraries', label: 'Libraries', type: 'text', regex: /libraries/i },
      { id: 'databases', label: 'Databases', type: 'text', regex: /databases/i },
      { id: 'cloudTechnologies', label: 'Cloud Technologies', type: 'text', regex: /cloud.*technologies/i },
      { id: 'devopsTools', label: 'DevOps Tools', type: 'text', regex: /devops.*tools/i },
      { id: 'testingTools', label: 'Testing Tools', type: 'text', regex: /testing.*tools/i },
      { id: 'versionControl', label: 'Version Control', type: 'text', regex: /version.*control/i },
      { id: 'otherTechnologies', label: 'Other Technologies', type: 'text', regex: /other.*technologies/i },
      { id: 'skillProficiency', label: 'Skill Proficiency', type: 'text', regex: /skill.*proficiency/i },
      { id: 'yearsOfExperienceWithSkill', label: 'Years of Experience with Skill', type: 'text', regex: /years.*of.*experience.*with.*skill/i },
      { id: 'skillRating', label: 'Skill Rating', type: 'text', regex: /skill.*rating/i },
      { id: 'primaryProgrammingLanguage', label: 'Primary Programming Language', type: 'text', regex: /primary.*programming.*language/i },
      { id: 'preferredProgrammingLanguage', label: 'Preferred Programming Language', type: 'text', regex: /preferred.*programming.*language/i },
      { id: 'mostComfortableLanguage', label: 'Most Comfortable Language', type: 'text', regex: /most.*comfortable.*language/i },
    ]
  },
  {
    id: 'developmentSkills',
    title: 'Development Skills',
    icon: 'CheckCircle2',
    fields: [
      { id: 'reactExperience', label: 'React Experience', type: 'text', regex: /react.*experience/i },
      { id: 'nodejsExperience', label: 'Nodejs Experience', type: 'text', regex: /nodejs.*experience/i },
      { id: 'expressExperience', label: 'Express Experience', type: 'text', regex: /express.*experience/i },
      { id: 'mongodbExperience', label: 'MongoDB Experience', type: 'text', regex: /mongodb.*experience/i },
      { id: 'mysqlExperience', label: 'MySQL Experience', type: 'text', regex: /mysql.*experience/i },
      { id: 'redisExperience', label: 'Redis Experience', type: 'text', regex: /redis.*experience/i },
      { id: 'reduxExperience', label: 'Redux Experience', type: 'text', regex: /redux.*experience/i },
      { id: 'nextjsExperience', label: 'Nextjs Experience', type: 'text', regex: /nextjs.*experience/i },
      { id: 'tailwindExperience', label: 'Tailwind Experience', type: 'text', regex: /tailwind.*experience/i },
      { id: 'awsExperience', label: 'AWS Experience', type: 'text', regex: /aws.*experience/i },
      { id: 'gitExperience', label: 'Git Experience', type: 'text', regex: /git.*experience/i },
      { id: 'restApiExperience', label: 'REST API Experience', type: 'text', regex: /rest.*api.*experience/i },
      { id: 'apiDevelopmentExperience', label: 'API Development Experience', type: 'text', regex: /api.*development.*experience/i },
      { id: 'fullStackDevelopmentExperience', label: 'Full Stack Development Experience', type: 'text', regex: /full.*stack.*development.*experience/i },
    ]
  },
  {
    id: 'projects',
    title: 'Projects',
    icon: 'CheckCircle2',
    isArray: true,
    fields: [
      { id: 'doYouHaveProjects', label: 'Do you have projects', type: 'text', regex: /do.*you.*have.*projects/i },
      { id: 'projectName', label: 'Project Name', type: 'text', regex: /project.*name/i },
      { id: 'projectDescription', label: 'Project Description', type: 'text', regex: /project.*description/i },
      { id: 'projectLink', label: 'Project Link', type: 'text', regex: /project.*link/i },
      { id: 'githubLink', label: 'GitHub Link', type: 'text', regex: /github.*link/i },
      { id: 'liveDemo', label: 'Live Demo', type: 'text', regex: /live.*demo/i },
      { id: 'projectDuration', label: 'Project Duration', type: 'text', regex: /project.*duration/i },
      { id: 'projectStartDate', label: 'Project Start Date', type: 'text', regex: /project.*start.*date/i },
      { id: 'projectEndDate', label: 'Project End Date', type: 'text', regex: /project.*end.*date/i },
      { id: 'yourRole', label: 'Your Role', type: 'text', regex: /your.*role/i },
      { id: 'teamSize', label: 'Team Size', type: 'text', regex: /team.*size/i },
      { id: 'technologiesUsed', label: 'Technologies Used', type: 'text', regex: /technologies.*used/i },
      { id: 'programmingLanguagesUsed', label: 'Programming Languages Used', type: 'text', regex: /programming.*languages.*used/i },
      { id: 'whatProblemDoesItSolve', label: 'What problem does it solve', type: 'text', regex: /what.*problem.*does.*it.*solve/i },
      { id: 'whyDidYouBuildIt', label: 'Why did you build it', type: 'text', regex: /why.*did.*you.*build.*it/i },
      { id: 'whatWasYourContribution', label: 'What was your contribution', type: 'text', regex: /what.*was.*your.*contribution/i },
      { id: 'biggestChallenge', label: 'Biggest challenge', type: 'text', regex: /biggest.*challenge/i },
      { id: 'howDidYouSolveTheChallenge', label: 'How did you solve the challenge', type: 'text', regex: /how.*did.*you.*solve.*the.*challenge/i },
      { id: 'numberOfUsers', label: 'Number of users', type: 'text', regex: /number.*of.*users/i },
      { id: 'realUsers', label: 'Real users', type: 'text', regex: /real.*users/i },
      { id: 'productionDeployed', label: 'Production deployed', type: 'text', regex: /production.*deployed/i },
      { id: 'projectArchitecture', label: 'Project architecture', type: 'text', regex: /project.*architecture/i },
      { id: 'backendUsed', label: 'Backend used', type: 'text', regex: /backend.*used/i },
      { id: 'databaseUsed', label: 'Database used', type: 'text', regex: /database.*used/i },
      { id: 'apiUsed', label: 'API used', type: 'text', regex: /api.*used/i },
      { id: 'aiUsed', label: 'AI used', type: 'text', regex: /ai.*used/i },
      { id: 'aiTechnologiesUsed', label: 'AI technologies used', type: 'text', regex: /ai.*technologies.*used/i },
      { id: 'projectDemoVideo', label: 'Project demo video', type: 'text', regex: /project.*demo.*video/i },
      { id: 'project1', label: 'Project 1', type: 'text', regex: /project.*1/i },
      { id: 'project2', label: 'Project 2', type: 'text', regex: /project.*2/i },
      { id: 'project3', label: 'Project 3', type: 'text', regex: /project.*3/i },
      { id: 'becauseSomeFormsAskForUpTo3Projects', label: 'because some forms ask for up to 3 projects', type: 'text', regex: /because.*some.*forms.*ask.*for.*up.*to.*3.*projects/i },
    ]
  },
  {
    id: 'achievements',
    title: 'Achievements',
    icon: 'CheckCircle2',
    fields: [
      { id: 'biggestAchievement', label: 'Biggest Achievement', type: 'text', regex: /biggest.*achievement/i },
      { id: 'academicAchievement', label: 'Academic Achievement', type: 'text', regex: /academic.*achievement/i },
      { id: 'technicalAchievement', label: 'Technical Achievement', type: 'text', regex: /technical.*achievement/i },
      { id: 'personalAchievement', label: 'Personal Achievement', type: 'text', regex: /personal.*achievement/i },
      { id: 'competitionAchievement', label: 'Competition Achievement', type: 'text', regex: /competition.*achievement/i },
      { id: 'codingAchievement', label: 'Coding Achievement', type: 'text', regex: /coding.*achievement/i },
      { id: 'hackathonAchievement', label: 'Hackathon Achievement', type: 'text', regex: /hackathon.*achievement/i },
      { id: 'awardReceived', label: 'Award Received', type: 'text', regex: /award.*received/i },
      { id: 'recognitionReceived', label: 'Recognition Received', type: 'text', regex: /recognition.*received/i },
      { id: 'rank', label: 'Rank', type: 'text', regex: /rank/i },
      { id: 'contestRating', label: 'Contest Rating', type: 'text', regex: /contest.*rating/i },
      { id: 'competitionPosition', label: 'Competition Position', type: 'text', regex: /competition.*position/i },
      { id: 'accomplishmentYoureProudOf', label: 'Accomplishment youre proud of', type: 'text', regex: /accomplishment.*youre.*proud.*of/i },
    ]
  },
  {
    id: 'certifications',
    title: 'Certifications',
    icon: 'CheckCircle2',
    fields: [
      { id: 'doYouHaveCertifications', label: 'Do you have certifications', type: 'text', regex: /do.*you.*have.*certifications/i },
      { id: 'certificationName', label: 'Certification Name', type: 'text', regex: /certification.*name/i },
      { id: 'certificationProvider', label: 'Certification Provider', type: 'text', regex: /certification.*provider/i },
      { id: 'certificationId', label: 'Certification ID', type: 'text', regex: /certification.*id/i },
      { id: 'issueDate', label: 'Issue Date', type: 'text', regex: /issue.*date/i },
      { id: 'expiryDate', label: 'Expiry Date', type: 'text', regex: /expiry.*date/i },
      { id: 'certificateUrl', label: 'Certificate URL', type: 'text', regex: /certificate.*url/i },
      { id: 'certificationDescription', label: 'Certification Description', type: 'text', regex: /certification.*description/i },
      { id: 'relevantCertification', label: 'Relevant Certification', type: 'text', regex: /relevant.*certification/i },
      { id: 'professionalCertification', label: 'Professional Certification', type: 'text', regex: /professional.*certification/i },
    ]
  },
  {
    id: 'codingProfiles',
    title: 'Coding Profiles',
    icon: 'CheckCircle2',
    fields: [
      { id: 'leetcodeProfile', label: 'LeetCode Profile', type: 'text', regex: /leetcode.*profile/i },
      { id: 'leetcodeRating', label: 'LeetCode Rating', type: 'text', regex: /leetcode.*rating/i },
      { id: 'leetcodeProblemsSolved', label: 'LeetCode Problems Solved', type: 'text', regex: /leetcode.*problems.*solved/i },
      { id: 'codechefProfile', label: 'CodeChef Profile', type: 'text', regex: /codechef.*profile/i },
      { id: 'codechefRating', label: 'CodeChef Rating', type: 'text', regex: /codechef.*rating/i },
      { id: 'codeforcesProfile', label: 'Codeforces Profile', type: 'text', regex: /codeforces.*profile/i },
      { id: 'codeforcesRating', label: 'Codeforces Rating', type: 'text', regex: /codeforces.*rating/i },
      { id: 'geeksforgeeksProfile', label: 'GeeksforGeeks Profile', type: 'text', regex: /geeksforgeeks.*profile/i },
      { id: 'gfgProblemsSolved', label: 'GFG Problems Solved', type: 'text', regex: /gfg.*problems.*solved/i },
      { id: 'hackerrankProfile', label: 'HackerRank Profile', type: 'text', regex: /hackerrank.*profile/i },
      { id: 'hackerrankScore', label: 'HackerRank Score', type: 'text', regex: /hackerrank.*score/i },
      { id: 'codingNinjasProfile', label: 'Coding Ninjas Profile', type: 'text', regex: /coding.*ninjas.*profile/i },
      { id: 'linkedinProfile', label: 'LinkedIn Profile', type: 'text', regex: /linkedin.*profile/i },
      { id: 'portfolioWebsite', label: 'Portfolio Website', type: 'text', regex: /portfolio.*website/i },
    ]
  },
  {
    id: 'hackathonsCompetitions',
    title: 'Hackathons / Competitions',
    icon: 'CheckCircle2',
    fields: [
      { id: 'haveYouParticipatedInAHackathon', label: 'Have you participated in a hackathon', type: 'text', regex: /have.*you.*participated.*in.*a.*hackathon/i },
      { id: 'hackathonName', label: 'Hackathon Name', type: 'text', regex: /hackathon.*name/i },
      { id: 'organization', label: 'Organization', type: 'text', regex: /organization/i },
      { id: 'date', label: 'Date', type: 'text', regex: /date/i },
      { id: 'teamSize', label: 'Team Size', type: 'text', regex: /team.*size/i },
      { id: 'yourRole', label: 'Your Role', type: 'text', regex: /your.*role/i },
      { id: 'projectBuilt', label: 'Project Built', type: 'text', regex: /project.*built/i },
      { id: 'positionRank', label: 'Position/Rank', type: 'text', regex: /position.*rank/i },
      { id: 'certificate', label: 'Certificate', type: 'text', regex: /certificate/i },
      { id: 'hackathonLink', label: 'Hackathon Link', type: 'text', regex: /hackathon.*link/i },
      { id: 'competitionName', label: 'Competition Name', type: 'text', regex: /competition.*name/i },
      { id: 'competitionResult', label: 'Competition Result', type: 'text', regex: /competition.*result/i },
    ]
  },
  {
    id: 'leadershipExtracurricular',
    title: 'Leadership / Extracurricular',
    icon: 'CheckCircle2',
    fields: [
      { id: 'leadershipExperience', label: 'Leadership Experience', type: 'text', regex: /leadership.*experience/i },
      { id: 'clubName', label: 'Club Name', type: 'text', regex: /club.*name/i },
      { id: 'organizationName', label: 'Organization Name', type: 'text', regex: /organization.*name/i },
      { id: 'position', label: 'Position', type: 'text', regex: /position/i },
      { id: 'role', label: 'Role', type: 'text', regex: /role/i },
      { id: 'duration', label: 'Duration', type: 'text', regex: /duration/i },
      { id: 'teamSize', label: 'Team Size', type: 'text', regex: /team.*size/i },
      { id: 'responsibilities', label: 'Responsibilities', type: 'text', regex: /responsibilities/i },
      { id: 'impact', label: 'Impact', type: 'text', regex: /impact/i },
      { id: 'ngoExperience', label: 'NGO Experience', type: 'text', regex: /ngo.*experience/i },
      { id: 'studentChapter', label: 'Student Chapter', type: 'text', regex: /student.*chapter/i },
      { id: 'collegeClub', label: 'College Club', type: 'text', regex: /college.*club/i },
      { id: 'volunteerExperience', label: 'Volunteer Experience', type: 'text', regex: /volunteer.*experience/i },
      { id: 'eventOrganized', label: 'Event Organized', type: 'text', regex: /event.*organized/i },
      { id: 'eventParticipation', label: 'Event Participation', type: 'text', regex: /event.*participation/i },
    ]
  },
  {
    id: 'personalityQuestions',
    title: 'Personality Questions',
    icon: 'CheckCircle2',
    fields: [
      { id: 'tellUsAboutYourself', label: 'Tell us about yourself', type: 'text', regex: /tell.*us.*about.*yourself/i },
      { id: 'introduceYourself', label: 'Introduce yourself', type: 'text', regex: /introduce.*yourself/i },
      { id: 'describeYourself', label: 'Describe yourself', type: 'text', regex: /describe.*yourself/i },
      { id: 'whatAreYourStrengths', label: 'What are your strengths', type: 'text', regex: /what.*are.*your.*strengths/i },
      { id: 'whatAreYourWeaknesses', label: 'What are your weaknesses', type: 'text', regex: /what.*are.*your.*weaknesses/i },
      { id: 'whatIsYourBiggestStrength', label: 'What is your biggest strength', type: 'text', regex: /what.*is.*your.*biggest.*strength/i },
      { id: 'whatIsYourImprovementArea', label: 'What is your improvement area', type: 'text', regex: /what.*is.*your.*improvement.*area/i },
      { id: 'whatMakesYouDifferent', label: 'What makes you different', type: 'text', regex: /what.*makes.*you.*different/i },
      { id: 'whatMakesYouStandOut', label: 'What makes you stand out', type: 'text', regex: /what.*makes.*you.*stand.*out/i },
      { id: 'whatIsYourStandoutQuality', label: 'What is your standout quality', type: 'text', regex: /what.*is.*your.*standout.*quality/i },
      { id: 'whatMotivatesYou', label: 'What motivates you', type: 'text', regex: /what.*motivates.*you/i },
      { id: 'whatInspiresYou', label: 'What inspires you', type: 'text', regex: /what.*inspires.*you/i },
      { id: 'whatAreYouPassionateAbout', label: 'What are you passionate about', type: 'text', regex: /what.*are.*you.*passionate.*about/i },
      { id: 'whatAreYourInterests', label: 'What are your interests', type: 'text', regex: /what.*are.*your.*interests/i },
      { id: 'whatAreYourHobbies', label: 'What are your hobbies', type: 'text', regex: /what.*are.*your.*hobbies/i },
      { id: 'whatDoYouEnjoyDoing', label: 'What do you enjoy doing', type: 'text', regex: /what.*do.*you.*enjoy.*doing/i },
      { id: 'whatIsSomethingPeopleDontKnowAboutYou', label: 'What is something people dont know about you', type: 'text', regex: /what.*is.*something.*people.*dont.*know.*about.*you/i },
    ]
  },
  {
    id: 'careerQuestions',
    title: 'Career Questions',
    icon: 'CheckCircle2',
    fields: [
      { id: 'whatAreYourCareerGoals', label: 'What are your career goals', type: 'text', regex: /what.*are.*your.*career.*goals/i },
      { id: 'whereDoYouSeeYourselfIn5Years', label: 'Where do you see yourself in 5 years', type: 'text', regex: /where.*do.*you.*see.*yourself.*in.*5.*years/i },
      { id: 'whatAreYourShortTermGoals', label: 'What are your short-term goals', type: 'text', regex: /what.*are.*your.*short.*term.*goals/i },
      { id: 'whatAreYourLongTermGoals', label: 'What are your long-term goals', type: 'text', regex: /what.*are.*your.*long.*term.*goals/i },
      { id: 'whatTypeOfRoleAreYouLookingFor', label: 'What type of role are you looking for', type: 'text', regex: /what.*type.*of.*role.*are.*you.*looking.*for/i },
      { id: 'whatAreYouLookingForInYourNextJob', label: 'What are you looking for in your next job', type: 'text', regex: /what.*are.*you.*looking.*for.*in.*your.*next.*job/i },
      { id: 'whyThisRole', label: 'Why this role', type: 'text', regex: /why.*this.*role/i },
      { id: 'whyThisCompany', label: 'Why this company', type: 'text', regex: /why.*this.*company/i },
      { id: 'whyShouldWeHireYou', label: 'Why should we hire you', type: 'text', regex: /why.*should.*we.*hire.*you/i },
      { id: 'whyAreYouInterestedInThisOpportunity', label: 'Why are you interested in this opportunity', type: 'text', regex: /why.*are.*you.*interested.*in.*this.*opportunity/i },
      { id: 'whatMotivatesYouToApply', label: 'What motivates you to apply', type: 'text', regex: /what.*motivates.*you.*to.*apply/i },
      { id: 'whatAreYourCareerInterests', label: 'What are your career interests', type: 'text', regex: /what.*are.*your.*career.*interests/i },
      { id: 'whatIsYourDreamJob', label: 'What is your dream job', type: 'text', regex: /what.*is.*your.*dream.*job/i },
    ]
  },
  {
    id: 'companySpecificQuestions',
    title: 'Company-Specific Questions',
    icon: 'CheckCircle2',
    fields: [
      { id: 'whyDoYouWantToJoinUs', label: 'Why do you want to join us', type: 'text', regex: /why.*do.*you.*want.*to.*join.*us/i },
      { id: 'whyDoYouWantToWorkHere', label: 'Why do you want to work here', type: 'text', regex: /why.*do.*you.*want.*to.*work.*here/i },
      { id: 'whyThisCompany', label: 'Why this company', type: 'text', regex: /why.*this.*company/i },
      { id: 'whatDoYouKnowAboutOurCompany', label: 'What do you know about our company', type: 'text', regex: /what.*do.*you.*know.*about.*our.*company/i },
      { id: 'whatInterestsYouAboutOurProduct', label: 'What interests you about our product', type: 'text', regex: /what.*interests.*you.*about.*our.*product/i },
      { id: 'whatInterestsYouAboutThisRole', label: 'What interests you about this role', type: 'text', regex: /what.*interests.*you.*about.*this.*role/i },
      { id: 'whyShouldWeSelectYou', label: 'Why should we select you', type: 'text', regex: /why.*should.*we.*select.*you/i },
      { id: 'whatValueCanYouBring', label: 'What value can you bring', type: 'text', regex: /what.*value.*can.*you.*bring/i },
      { id: 'whatMakesYouSuitableForThisPosition', label: 'What makes you suitable for this position', type: 'text', regex: /what.*makes.*you.*suitable.*for.*this.*position/i },
      { id: 'whatDoYouExpectFromThisInternship', label: 'What do you expect from this internship', type: 'text', regex: /what.*do.*you.*expect.*from.*this.*internship/i },
      { id: 'whatDoYouExpectFromThisJob', label: 'What do you expect from this job', type: 'text', regex: /what.*do.*you.*expect.*from.*this.*job/i },
    ]
  },
  {
    id: 'behavioralQuestions',
    title: 'Behavioral Questions',
    icon: 'CheckCircle2',
    fields: [
      { id: 'describeADifficultChallenge', label: 'Describe a difficult challenge', type: 'text', regex: /describe.*a.*difficult.*challenge/i },
      { id: 'tellUsAboutAChallengeYouFaced', label: 'Tell us about a challenge you faced', type: 'text', regex: /tell.*us.*about.*a.*challenge.*you.*faced/i },
      { id: 'howDidYouSolveAProblem', label: 'How did you solve a problem', type: 'text', regex: /how.*did.*you.*solve.*a.*problem/i },
      { id: 'tellUsAboutAFailure', label: 'Tell us about a failure', type: 'text', regex: /tell.*us.*about.*a.*failure/i },
      { id: 'whatDidYouLearnFromFailure', label: 'What did you learn from failure', type: 'text', regex: /what.*did.*you.*learn.*from.*failure/i },
      { id: 'tellUsAboutATimeYouMadeAMistake', label: 'Tell us about a time you made a mistake', type: 'text', regex: /tell.*us.*about.*a.*time.*you.*made.*a.*mistake/i },
      { id: 'tellUsAboutTeamwork', label: 'Tell us about teamwork', type: 'text', regex: /tell.*us.*about.*teamwork/i },
      { id: 'tellUsAboutAConflict', label: 'Tell us about a conflict', type: 'text', regex: /tell.*us.*about.*a.*conflict/i },
      { id: 'howDidYouResolveAConflict', label: 'How did you resolve a conflict', type: 'text', regex: /how.*did.*you.*resolve.*a.*conflict/i },
      { id: 'tellUsAboutLeadership', label: 'Tell us about leadership', type: 'text', regex: /tell.*us.*about.*leadership/i },
      { id: 'tellUsAboutATimeYouTookInitiative', label: 'Tell us about a time you took initiative', type: 'text', regex: /tell.*us.*about.*a.*time.*you.*took.*initiative/i },
      { id: 'tellUsAboutATimeYouWorkedUnderPressure', label: 'Tell us about a time you worked under pressure', type: 'text', regex: /tell.*us.*about.*a.*time.*you.*worked.*under.*pressure/i },
      { id: 'tellUsAboutADifficultDecision', label: 'Tell us about a difficult decision', type: 'text', regex: /tell.*us.*about.*a.*difficult.*decision/i },
      { id: 'tellUsAboutSomethingYouBuilt', label: 'Tell us about something you built', type: 'text', regex: /tell.*us.*about.*something.*you.*built/i },
      { id: 'whatWentWrong', label: 'What went wrong', type: 'text', regex: /what.*went.*wrong/i },
      { id: 'howDidYouHandleIt', label: 'How did you handle it', type: 'text', regex: /how.*did.*you.*handle.*it/i },
    ]
  },
  {
    id: 'aiQuestions',
    title: 'AI Questions',
    icon: 'CheckCircle2',
    fields: [
      { id: 'haveYouWorkedWithAi', label: 'Have you worked with AI', type: 'text', regex: /have.*you.*worked.*with.*ai/i },
      { id: 'aiProjects', label: 'AI projects', type: 'text', regex: /ai.*projects/i },
      { id: 'aiToolsUsed', label: 'AI tools used', type: 'text', regex: /ai.*tools.*used/i },
      { id: 'aiTechnologies', label: 'AI technologies', type: 'text', regex: /ai.*technologies/i },
      { id: 'aiProjectLink', label: 'AI project link', type: 'text', regex: /ai.*project.*link/i },
      { id: 'howDoYouUseAi', label: 'How do you use AI', type: 'text', regex: /how.*do.*you.*use.*ai/i },
      { id: 'describeYourAiWorkflow', label: 'Describe your AI workflow', type: 'text', regex: /describe.*your.*ai.*workflow/i },
      { id: 'haveYouBuiltAnAiApplication', label: 'Have you built an AI application', type: 'text', regex: /have.*you.*built.*an.*ai.*application/i },
      { id: 'whichAiApisHaveYouUsed', label: 'Which AI APIs have you used', type: 'text', regex: /which.*ai.*apis.*have.*you.*used/i },
      { id: 'generativeAiExperience', label: 'Generative AI experience', type: 'text', regex: /generative.*ai.*experience/i },
      { id: 'promptEngineeringExperience', label: 'Prompt engineering experience', type: 'text', regex: /prompt.*engineering.*experience/i },
    ]
  },
  {
    id: 'workAuthorization',
    title: 'Work Authorization',
    icon: 'CheckCircle2',
    fields: [
      { id: 'areYouAuthorizedToWorkInIndia', label: 'Are you authorized to work in India', type: 'text', regex: /are.*you.*authorized.*to.*work.*in.*india/i },
      { id: 'areYouLegallyAuthorizedToWork', label: 'Are you legally authorized to work', type: 'text', regex: /are.*you.*legally.*authorized.*to.*work/i },
      { id: 'doYouRequireSponsorship', label: 'Do you require sponsorship', type: 'text', regex: /do.*you.*require.*sponsorship/i },
      { id: 'willYouRequireSponsorshipInTheFuture', label: 'Will you require sponsorship in the future', type: 'text', regex: /will.*you.*require.*sponsorship.*in.*the.*future/i },
      { id: 'areYouACitizen', label: 'Are you a citizen', type: 'text', regex: /are.*you.*a.*citizen/i },
      { id: 'areYouAnOci', label: 'Are you an OCI', type: 'text', regex: /are.*you.*an.*oci/i },
      { id: 'workAuthorizationCountry', label: 'Work authorization country', type: 'text', regex: /work.*authorization.*country/i },
      { id: 'visaStatus', label: 'Visa status', type: 'text', regex: /visa.*status/i },
      { id: 'visaExpiry', label: 'Visa expiry', type: 'text', regex: /visa.*expiry/i },
      { id: 'passportStatus', label: 'Passport status', type: 'text', regex: /passport.*status/i },
    ]
  },
  {
    id: 'availability',
    title: 'Availability',
    icon: 'CheckCircle2',
    fields: [
      { id: 'whenCanYouStart', label: 'When can you start', type: 'text', regex: /when.*can.*you.*start/i },
      { id: 'internshipStartDate', label: 'Internship start date', type: 'text', regex: /internship.*start.*date/i },
      { id: 'internshipEndDate', label: 'Internship end date', type: 'text', regex: /internship.*end.*date/i },
      { id: 'availableFullTime', label: 'Available full-time', type: 'text', regex: /available.*full.*time/i },
      { id: 'availablePartTime', label: 'Available part-time', type: 'text', regex: /available.*part.*time/i },
      { id: 'hoursAvailablePerWeek', label: 'Hours available per week', type: 'text', regex: /hours.*available.*per.*week/i },
      { id: 'internshipDuration', label: 'Internship duration', type: 'text', regex: /internship.*duration/i },
      { id: 'preferredInternshipDuration', label: 'Preferred internship duration', type: 'text', regex: /preferred.*internship.*duration/i },
      { id: 'joiningDate', label: 'Joining date', type: 'text', regex: /joining.*date/i },
      { id: 'noticePeriod', label: 'Notice period', type: 'text', regex: /notice.*period/i },
      { id: 'earliestJoiningDate', label: 'Earliest joining date', type: 'text', regex: /earliest.*joining.*date/i },
      { id: 'areYouAvailableImmediately', label: 'Are you available immediately', type: 'text', regex: /are.*you.*available.*immediately/i },
    ]
  },
  {
    id: 'salaryCompensation',
    title: 'Salary / Compensation',
    icon: 'CheckCircle2',
    fields: [
      { id: 'expectedSalary', label: 'Expected Salary', type: 'text', regex: /expected.*salary/i },
      { id: 'expectedCtc', label: 'Expected CTC', type: 'text', regex: /expected.*ctc/i },
      { id: 'expectedBaseSalary', label: 'Expected Base Salary', type: 'text', regex: /expected.*base.*salary/i },
      { id: 'currentSalary', label: 'Current Salary', type: 'text', regex: /current.*salary/i },
      { id: 'currentCtc', label: 'Current CTC', type: 'text', regex: /current.*ctc/i },
      { id: 'previousCtc', label: 'Previous CTC', type: 'text', regex: /previous.*ctc/i },
      { id: 'expectedStipend', label: 'Expected Stipend', type: 'text', regex: /expected.*stipend/i },
      { id: 'currentStipend', label: 'Current Stipend', type: 'text', regex: /current.*stipend/i },
      { id: 'minimumExpectedSalary', label: 'Minimum Expected Salary', type: 'text', regex: /minimum.*expected.*salary/i },
      { id: 'salaryExpectations', label: 'Salary Expectations', type: 'text', regex: /salary.*expectations/i },
      { id: 'areYouFlexibleWithCompensation', label: 'Are you flexible with compensation', type: 'text', regex: /are.*you.*flexible.*with.*compensation/i },
    ]
  },
  {
    id: 'documents',
    title: 'Documents',
    icon: 'CheckCircle2',
    fields: [
      { id: 'resume', label: 'Resume', type: 'text', regex: /resume/i },
      { id: 'cv', label: 'CV', type: 'text', regex: /cv/i },
      { id: 'coverLetter', label: 'Cover Letter', type: 'text', regex: /cover.*letter/i },
      { id: 'photograph', label: 'Photograph', type: 'text', regex: /photograph/i },
      { id: 'signature', label: 'Signature', type: 'text', regex: /signature/i },
      { id: 'aadhaar', label: 'Aadhaar', type: 'text', regex: /aadhaar/i },
      { id: 'pan', label: 'PAN', type: 'text', regex: /pan/i },
      { id: 'passport', label: 'Passport', type: 'text', regex: /passport/i },
      { id: 'marksheet', label: 'Marksheet', type: 'text', regex: /marksheet/i },
      { id: '10ThCertificate', label: '10th Certificate', type: 'text', regex: /10th.*certificate/i },
      { id: '12ThCertificate', label: '12th Certificate', type: 'text', regex: /12th.*certificate/i },
      { id: 'degreeCertificate', label: 'Degree Certificate', type: 'text', regex: /degree.*certificate/i },
      { id: 'transcript', label: 'Transcript', type: 'text', regex: /transcript/i },
      { id: 'internshipCertificate', label: 'Internship Certificate', type: 'text', regex: /internship.*certificate/i },
      { id: 'experienceLetter', label: 'Experience Letter', type: 'text', regex: /experience.*letter/i },
      { id: 'offerLetter', label: 'Offer Letter', type: 'text', regex: /offer.*letter/i },
      { id: 'portfolio', label: 'Portfolio', type: 'text', regex: /portfolio/i },
      { id: 'videoResume', label: 'Video Resume', type: 'text', regex: /video.*resume/i },
      { id: 'introductionVideo', label: 'Introduction Video', type: 'text', regex: /introduction.*video/i },
    ]
  },
  {
    id: 'socialOnlinePresence',
    title: 'Social / Online Presence',
    icon: 'CheckCircle2',
    fields: [
      { id: 'linkedin', label: 'LinkedIn', type: 'text', regex: /linkedin/i },
      { id: 'github', label: 'GitHub', type: 'text', regex: /github/i },
      { id: 'portfolio', label: 'Portfolio', type: 'text', regex: /portfolio/i },
      { id: 'personalWebsite', label: 'Personal Website', type: 'text', regex: /personal.*website/i },
      { id: 'twitterX', label: 'Twitter/X', type: 'text', regex: /twitter.*x/i },
      { id: 'instagram', label: 'Instagram', type: 'text', regex: /instagram/i },
      { id: 'youtube', label: 'YouTube', type: 'text', regex: /youtube/i },
      { id: 'stackOverflow', label: 'Stack Overflow', type: 'text', regex: /stack.*overflow/i },
      { id: 'codingProfile', label: 'Coding Profile', type: 'text', regex: /coding.*profile/i },
      { id: 'blog', label: 'Blog', type: 'text', regex: /blog/i },
      { id: 'medium', label: 'Medium', type: 'text', regex: /medium/i },
      { id: 'otherWebsite', label: 'Other Website', type: 'text', regex: /other.*website/i },
    ]
  },
  {
    id: 'interestsSpecialQuestions',
    title: 'Interests / Special Questions',
    icon: 'CheckCircle2',
    fields: [
      { id: 'someCompaniesGoCompletelyOutsideNormalJobQuestions', label: 'Some companies go completely outside normal job questions', type: 'text', regex: /some.*companies.*go.*completely.*outside.*normal.*job.*questions/i },
      { id: 'favoriteGame', label: 'Favorite game', type: 'text', regex: /favorite.*game/i },
      { id: 'mobileGamesPlayed', label: 'Mobile games played', type: 'text', regex: /mobile.*games.*played/i },
      { id: 'howLongHaveYouPlayed', label: 'How long have you played', type: 'text', regex: /how.*long.*have.*you.*played/i },
      { id: 'currentGameLevel', label: 'Current game level', type: 'text', regex: /current.*game.*level/i },
      { id: 'favoriteTechnology', label: 'Favorite technology', type: 'text', regex: /favorite.*technology/i },
      { id: 'favoriteProgrammingLanguage', label: 'Favorite programming language', type: 'text', regex: /favorite.*programming.*language/i },
      { id: 'favoriteProject', label: 'Favorite project', type: 'text', regex: /favorite.*project/i },
      { id: 'interestingGameplayIdea', label: 'Interesting gameplay idea', type: 'text', regex: /interesting.*gameplay.*idea/i },
      { id: 'whatWouldYouChangeInAGame', label: 'What would you change in a game', type: 'text', regex: /what.*would.*you.*change.*in.*a.*game/i },
      { id: 'favoriteProduct', label: 'Favorite product', type: 'text', regex: /favorite.*product/i },
      { id: 'personalInterests', label: 'Personal interests', type: 'text', regex: /personal.*interests/i },
      { id: 'hobbies', label: 'Hobbies', type: 'text', regex: /hobbies/i },
      { id: 'books', label: 'Books', type: 'text', regex: /books/i },
      { id: 'movies', label: 'Movies', type: 'text', regex: /movies/i },
      { id: 'sports', label: 'Sports', type: 'text', regex: /sports/i },
    ]
  },
  {
    id: 'entrepreneurship',
    title: 'Entrepreneurship',
    icon: 'CheckCircle2',
    fields: [
      { id: 'haveYouStartedACompany', label: 'Have you started a company', type: 'text', regex: /have.*you.*started.*a.*company/i },
      { id: 'haveYouWorkedOnAStartup', label: 'Have you worked on a startup', type: 'text', regex: /have.*you.*worked.*on.*a.*startup/i },
      { id: 'startupName', label: 'Startup Name', type: 'text', regex: /startup.*name/i },
      { id: 'startupWebsite', label: 'Startup Website', type: 'text', regex: /startup.*website/i },
      { id: 'yourRole', label: 'Your Role', type: 'text', regex: /your.*role/i },
      { id: 'teamSize', label: 'Team Size', type: 'text', regex: /team.*size/i },
      { id: 'product', label: 'Product', type: 'text', regex: /product/i },
      { id: 'users', label: 'Users', type: 'text', regex: /users/i },
      { id: 'revenue', label: 'Revenue', type: 'text', regex: /revenue/i },
      { id: 'problemSolved', label: 'Problem Solved', type: 'text', regex: /problem.*solved/i },
      { id: 'entrepreneurialExperience', label: 'Entrepreneurial Experience', type: 'text', regex: /entrepreneurial.*experience/i },
    ]
  },
  {
    id: 'companyPreferences',
    title: 'Company Preferences',
    icon: 'CheckCircle2',
    fields: [
      { id: 'preferredJobFunction', label: 'Preferred Job Function', type: 'text', regex: /preferred.*job.*function/i },
      { id: 'preferredRole', label: 'Preferred Role', type: 'text', regex: /preferred.*role/i },
      { id: 'jobPreference1', label: 'Job Preference 1', type: 'text', regex: /job.*preference.*1/i },
      { id: 'jobPreference2', label: 'Job Preference 2', type: 'text', regex: /job.*preference.*2/i },
      { id: 'jobPreference3', label: 'Job Preference 3', type: 'text', regex: /job.*preference.*3/i },
      { id: 'preferredDepartment', label: 'Preferred Department', type: 'text', regex: /preferred.*department/i },
      { id: 'preferredIndustry', label: 'Preferred Industry', type: 'text', regex: /preferred.*industry/i },
      { id: 'preferredLocation', label: 'Preferred Location', type: 'text', regex: /preferred.*location/i },
      { id: 'preferredWorkMode', label: 'Preferred Work Mode', type: 'text', regex: /preferred.*work.*mode/i },
      { id: 'fullTimeInternship', label: 'Full-time/Internship', type: 'text', regex: /full.*time.*internship/i },
      { id: 'internshipJobPreference', label: 'Internship/Job Preference', type: 'text', regex: /internship.*job.*preference/i },
    ]
  },
  {
    id: 'eligibilityQuestions',
    title: 'Eligibility Questions',
    icon: 'CheckCircle2',
    fields: [
      { id: 'areYouCurrentlyEnrolled', label: 'Are you currently enrolled', type: 'text', regex: /are.*you.*currently.*enrolled/i },
      { id: 'areYouAFinalYearStudent', label: 'Are you a final-year student', type: 'text', regex: /are.*you.*a.*final.*year.*student/i },
      { id: 'graduationYear', label: 'Graduation year', type: 'text', regex: /graduation.*year/i },
      { id: 'minimumCgpaRequirementMet', label: 'Minimum CGPA requirement met', type: 'text', regex: /minimum.*cgpa.*requirement.*met/i },
      { id: '10ThPercentageRequirementMet', label: '10th percentage requirement met', type: 'text', regex: /10th.*percentage.*requirement.*met/i },
      { id: '12ThPercentageRequirementMet', label: '12th percentage requirement met', type: 'text', regex: /12th.*percentage.*requirement.*met/i },
      { id: 'anyActiveBacklogs', label: 'Any active backlogs', type: 'text', regex: /any.*active.*backlogs/i },
      { id: 'anyHistoryOfBacklogs', label: 'Any history of backlogs', type: 'text', regex: /any.*history.*of.*backlogs/i },
      { id: 'anyGapInEducation', label: 'Any gap in education', type: 'text', regex: /any.*gap.*in.*education/i },
      { id: 'haveYouPreviouslyApplied', label: 'Have you previously applied', type: 'text', regex: /have.*you.*previously.*applied/i },
      { id: 'haveYouPreviouslyInterviewed', label: 'Have you previously interviewed', type: 'text', regex: /have.*you.*previously.*interviewed/i },
      { id: 'areYouCurrentlyEmployed', label: 'Are you currently employed', type: 'text', regex: /are.*you.*currently.*employed/i },
      { id: 'areYouCurrentlyInterning', label: 'Are you currently interning', type: 'text', regex: /are.*you.*currently.*interning/i },
      { id: 'haveYouWorkedForThisCompanyBefore', label: 'Have you worked for this company before', type: 'text', regex: /have.*you.*worked.*for.*this.*company.*before/i },
      { id: 'areYouAnExEmployee', label: 'Are you an ex-employee', type: 'text', regex: /are.*you.*an.*ex.*employee/i },
      { id: 'areYouRelatedToAnEmployee', label: 'Are you related to an employee', type: 'text', regex: /are.*you.*related.*to.*an.*employee/i },
      { id: 'areYouEligibleToApply', label: 'Are you eligible to apply', type: 'text', regex: /are.*you.*eligible.*to.*apply/i },
    ]
  },
  {
    id: 'languages',
    title: 'Languages',
    icon: 'CheckCircle2',
    fields: [
      { id: 'languagesKnown', label: 'Languages Known', type: 'text', regex: /languages.*known/i },
      { id: 'englishProficiency', label: 'English Proficiency', type: 'text', regex: /english.*proficiency/i },
      { id: 'hindiProficiency', label: 'Hindi Proficiency', type: 'text', regex: /hindi.*proficiency/i },
      { id: 'nativeLanguage', label: 'Native Language', type: 'text', regex: /native.*language/i },
      { id: 'readingProficiency', label: 'Reading proficiency', type: 'text', regex: /reading.*proficiency/i },
      { id: 'writingProficiency', label: 'Writing proficiency', type: 'text', regex: /writing.*proficiency/i },
      { id: 'speakingProficiency', label: 'Speaking proficiency', type: 'text', regex: /speaking.*proficiency/i },
      { id: 'listeningProficiency', label: 'Listening proficiency', type: 'text', regex: /listening.*proficiency/i },
      { id: 'foreignLanguages', label: 'Foreign Languages', type: 'text', regex: /foreign.*languages/i },
      { id: 'languageCertification', label: 'Language Certification', type: 'text', regex: /language.*certification/i },
    ]
  },
  {
    id: 'openEndedQuestions',
    title: 'Open-Ended Questions',
    icon: 'CheckCircle2',
    fields: [
      { id: 'tellUsSomethingAboutYourself', label: 'Tell us something about yourself', type: 'text', regex: /tell.*us.*something.*about.*yourself/i },
      { id: 'tellUsAboutYourBackground', label: 'Tell us about your background', type: 'text', regex: /tell.*us.*about.*your.*background/i },
      { id: 'describeYourBiggestAccomplishment', label: 'Describe your biggest accomplishment', type: 'text', regex: /describe.*your.*biggest.*accomplishment/i },
      { id: 'describeYourBiggestFailure', label: 'Describe your biggest failure', type: 'text', regex: /describe.*your.*biggest.*failure/i },
      { id: 'describeYourStrongestSkill', label: 'Describe your strongest skill', type: 'text', regex: /describe.*your.*strongest.*skill/i },
      { id: 'describeYourWeakestSkill', label: 'Describe your weakest skill', type: 'text', regex: /describe.*your.*weakest.*skill/i },
      { id: 'describeYourFavoriteProject', label: 'Describe your favorite project', type: 'text', regex: /describe.*your.*favorite.*project/i },
      { id: 'describeYourIdealWorkplace', label: 'Describe your ideal workplace', type: 'text', regex: /describe.*your.*ideal.*workplace/i },
      { id: 'describeYourIdealJob', label: 'Describe your ideal job', type: 'text', regex: /describe.*your.*ideal.*job/i },
      { id: 'describeYourBiggestChallenge', label: 'Describe your biggest challenge', type: 'text', regex: /describe.*your.*biggest.*challenge/i },
      { id: 'whatAreYouMostProudOf', label: 'What are you most proud of', type: 'text', regex: /what.*are.*you.*most.*proud.*of/i },
      { id: 'whatWouldYouLikeToImprove', label: 'What would you like to improve', type: 'text', regex: /what.*would.*you.*like.*to.*improve/i },
      { id: 'whatMakesYouUnique', label: 'What makes you unique', type: 'text', regex: /what.*makes.*you.*unique/i },
      { id: 'anythingElseYoudLikeUsToKnow', label: 'Anything else youd like us to know', type: 'text', regex: /anything.*else.*youd.*like.*us.*to.*know/i },
    ]
  },
  {
    id: 'legalConsent',
    title: 'Legal / Consent',
    icon: 'CheckCircle2',
    fields: [
      { id: 'agreeToTermsConditions', label: 'Agree to Terms  Conditions', type: 'text', regex: /agree.*to.*terms.*.*conditions/i },
      { id: 'privacyPolicyConsent', label: 'Privacy Policy consent', type: 'text', regex: /privacy.*policy.*consent/i },
      { id: 'dataProcessingConsent', label: 'Data processing consent', type: 'text', regex: /data.*processing.*consent/i },
      { id: 'backgroundVerificationConsent', label: 'Background verification consent', type: 'text', regex: /background.*verification.*consent/i },
      { id: 'marketingCommunicationConsent', label: 'Marketing communication consent', type: 'text', regex: /marketing.*communication.*consent/i },
      { id: 'jobAlertConsent', label: 'Job alert consent', type: 'text', regex: /job.*alert.*consent/i },
      { id: 'informationAccuracyConfirmation', label: 'Information accuracy confirmation', type: 'text', regex: /information.*accuracy.*confirmation/i },
      { id: 'electronicSignature', label: 'Electronic signature', type: 'text', regex: /electronic.*signature/i },
      { id: 'declaration', label: 'Declaration', type: 'text', regex: /declaration/i },
      { id: 'theseShouldNeverAllBeBlindlyCheckedByYourExtension', label: 'These should never all be blindly checked by your extension', type: 'text', regex: /these.*should.*never.*all.*be.*blindly.*checked.*by.*your.*extension/i },
      { id: '36FormMetadataVeryImportantForYourExtension', label: '36 Form Metadata  VERY IMPORTANT FOR YOUR EXTENSION', type: 'text', regex: /36.*form.*metadata.*.*very.*important.*for.*your.*extension/i },
      { id: 'theseArentQuestionsAskedToTheApplicantButYourExtensionShouldInternallyTrackThem', label: 'These arent questions asked to the applicant but your extension should internally track them', type: 'text', regex: /these.*arent.*questions.*asked.*to.*the.*applicant.*but.*your.*extension.*should.*internally.*track.*them/i },
      { id: 'company', label: 'Company', type: 'text', regex: /company/i },
      { id: 'jobTitle', label: 'Job Title', type: 'text', regex: /job.*title/i },
      { id: 'jobId', label: 'Job ID', type: 'text', regex: /job.*id/i },
      { id: 'applicationUrl', label: 'Application URL', type: 'text', regex: /application.*url/i },
      { id: 'formUrl', label: 'Form URL', type: 'text', regex: /form.*url/i },
      { id: 'detectedPlatform', label: 'Detected Platform', type: 'text', regex: /detected.*platform/i },
      { id: 'date', label: 'Date', type: 'text', regex: /date/i },
      { id: 'time', label: 'Time', type: 'text', regex: /time/i },
      { id: 'numberOfFields', label: 'Number of fields', type: 'text', regex: /number.*of.*fields/i },
      { id: 'fieldsAutomaticallyFilled', label: 'Fields automatically filled', type: 'text', regex: /fields.*automatically.*filled/i },
      { id: 'fieldsRequiringReview', label: 'Fields requiring review', type: 'text', regex: /fields.*requiring.*review/i },
      { id: 'fieldsSkipped', label: 'Fields skipped', type: 'text', regex: /fields.*skipped/i },
      { id: 'fieldsManuallyChanged', label: 'Fields manually changed', type: 'text', regex: /fields.*manually.*changed/i },
      { id: 'resumeUsed', label: 'Resume used', type: 'text', regex: /resume.*used/i },
      { id: 'answersUsed', label: 'Answers used', type: 'text', regex: /answers.*used/i },
      { id: 'submissionStatus', label: 'Submission status', type: 'text', regex: /submission.*status/i },
      { id: 'butDontCreate500DatabaseColumns', label: 'But dont create 500 database columns', type: 'text', regex: /but.*dont.*create.*500.*database.*columns/i },
      { id: 'thisIsTheImportantPartForYourProject', label: 'This is the important part for your project', type: 'text', regex: /this.*is.*the.*important.*part.*for.*your.*project/i },
      { id: 'youShouldNotCreate', label: 'You should NOT create', type: 'text', regex: /you.*should.*not.*create/i },
      { id: 'firstname', label: 'firstName', type: 'text', regex: /firstname/i },
      { id: 'lastname', label: 'lastName', type: 'text', regex: /lastname/i },
      { id: 'fathername', label: 'fatherName', type: 'text', regex: /fathername/i },
      { id: 'mothername', label: 'motherName', type: 'text', regex: /mothername/i },
      { id: 'phone', label: 'phone', type: 'text', regex: /phone/i },
      { id: 'phone2', label: 'phone2', type: 'text', regex: /phone2/i },
      { id: 'phone3', label: 'phone3', type: 'text', regex: /phone3/i },
      { id: 'as500UnrelatedFields', label: 'as 500 unrelated fields', type: 'text', regex: /as.*500.*unrelated.*fields/i },
      { id: 'buildAStructuredProfile', label: 'Build a structured profile', type: 'text', regex: /build.*a.*structured.*profile/i },
      { id: 'user', label: 'USER', type: 'text', regex: /user/i },
      { id: 'personal', label: 'Personal', type: 'text', regex: /personal/i },
      { id: 'name', label: 'name', type: 'text', regex: /name/i },
      { id: 'dob', label: 'dob', type: 'text', regex: /dob/i },
      { id: 'gender', label: 'gender', type: 'text', regex: /gender/i },
      { id: 'nationality', label: 'nationality', type: 'text', regex: /nationality/i },
      { id: 'citizenship', label: 'citizenship', type: 'text', regex: /citizenship/i },
      { id: 'contact', label: 'Contact', type: 'text', regex: /contact/i },
      { id: 'emails', label: 'emails', type: 'text', regex: /emails/i },
      { id: 'phones', label: 'phones', type: 'text', regex: /phones/i },
      { id: 'addresses', label: 'addresses', type: 'text', regex: /addresses/i },
      { id: 'education', label: 'Education', type: 'text', regex: /education/i },
      { id: 'secondary', label: 'secondary', type: 'text', regex: /secondary/i },
      { id: 'highersecondary', label: 'higherSecondary', type: 'text', regex: /highersecondary/i },
      { id: 'diploma', label: 'diploma', type: 'text', regex: /diploma/i },
      { id: 'undergraduate', label: 'undergraduate', type: 'text', regex: /undergraduate/i },
      { id: 'postgraduate', label: 'postgraduate', type: 'text', regex: /postgraduate/i },
      { id: 'experience', label: 'Experience', type: 'text', regex: /experience/i },
      { id: 'work', label: 'work', type: 'text', regex: /work/i },
      { id: 'internships', label: 'internships', type: 'text', regex: /internships/i },
      { id: 'skills', label: 'Skills', type: 'text', regex: /skills/i },
      { id: 'programming', label: 'programming', type: 'text', regex: /programming/i },
      { id: 'frameworks', label: 'frameworks', type: 'text', regex: /frameworks/i },
      { id: 'databases', label: 'databases', type: 'text', regex: /databases/i },
      { id: 'tools', label: 'tools', type: 'text', regex: /tools/i },
      { id: 'projects', label: 'Projects', type: 'text', regex: /projects/i },
      { id: 'certifications', label: 'Certifications', type: 'text', regex: /certifications/i },
      { id: 'achievements', label: 'Achievements', type: 'text', regex: /achievements/i },
      { id: 'codingprofiles', label: 'CodingProfiles', type: 'text', regex: /codingprofiles/i },
      { id: 'documents', label: 'Documents', type: 'text', regex: /documents/i },
      { id: 'preferences', label: 'Preferences', type: 'text', regex: /preferences/i },
      { id: 'availability', label: 'Availability', type: 'text', regex: /availability/i },
      { id: 'answervault', label: 'AnswerVault', type: 'text', regex: /answervault/i },
      { id: 'thenAFormSaying', label: 'Then a form saying', type: 'text', regex: /then.*a.*form.*saying/i },
      { id: 'mobileNumber', label: 'Mobile Number', type: 'text', regex: /mobile.*number/i },
      { id: 'getsMappedTo', label: 'gets mapped to', type: 'text', regex: /gets.*mapped.*to/i },
      { id: 'formQuestion', label: 'Form question', type: 'text', regex: /form.*question/i },
      { id: 'mobileNumber', label: 'Mobile Number', type: 'text', regex: /mobile.*number/i },
      { id: 'fieldClassifier', label: 'Field classifier', type: 'text', regex: /field.*classifier/i },
      { id: 'contactphonesprimary', label: 'contactphonesprimary', type: 'text', regex: /contactphonesprimary/i },
      { id: '91XxxxxXxxxx', label: '91 XXXXX XXXXX', type: 'text', regex: /91.*xxxxx.*xxxxx/i },
      { id: 'while', label: 'While', type: 'text', regex: /while/i },
      { id: 'emergencyContactNumber', label: 'Emergency Contact Number', type: 'text', regex: /emergency.*contact.*number/i },
      { id: 'mapsTo', label: 'maps to', type: 'text', regex: /maps.*to/i },
      { id: 'contactemergencyphone', label: 'contactemergencyphone', type: 'text', regex: /contactemergencyphone/i },
      { id: 'insteadOfAccidentallyUsingTheUsersOwnPhone', label: 'instead of accidentally using the users own phone', type: 'text', regex: /instead.*of.*accidentally.*using.*the.*users.*own.*phone/i },
      { id: 'andThisGivesYouAnEvenBiggerIdea', label: 'And this gives you an even bigger idea', type: 'text', regex: /and.*this.*gives.*you.*an.*even.*bigger.*idea/i },
      { id: 'dontJustBuild', label: 'Dont just build', type: 'text', regex: /dont.*just.*build/i },
      { id: 'autofillExtension', label: 'Autofill Extension', type: 'text', regex: /autofill.*extension/i },
      { id: 'build', label: 'Build', type: 'text', regex: /build/i },
      { id: 'personalApplicationProfile', label: 'Personal Application Profile', type: 'text', regex: /personal.*application.*profile/i },
      { id: 'theUserFillsTheirInformationOnce', label: 'The user fills their information once', type: 'text', regex: /the.*user.*fills.*their.*information.*once/i },
      { id: 'thenYourExtensionUnderstands', label: 'Then your extension understands', type: 'text', regex: /then.*your.*extension.*understands/i },
      { id: 'googleForms', label: 'Google Forms', type: 'text', regex: /google.*forms/i },
      { id: 'workday', label: 'Workday', type: 'text', regex: /workday/i },
      { id: 'greenhouse', label: 'Greenhouse', type: 'text', regex: /greenhouse/i },
      { id: 'lever', label: 'Lever', type: 'text', regex: /lever/i },
      { id: 'companyCareerPages', label: 'Company Career Pages', type: 'text', regex: /company.*career.*pages/i },
      { id: 'collegePlacementForms', label: 'College Placement Forms', type: 'text', regex: /college.*placement.*forms/i },
      { id: 'internshipForms', label: 'Internship Forms', type: 'text', regex: /internship.*forms/i },
      { id: 'competitionForms', label: 'Competition Forms', type: 'text', regex: /competition.*forms/i },
      { id: 'scholarshipForms', label: 'Scholarship Forms', type: 'text', regex: /scholarship.*forms/i },
      { id: 'recruitmentForms', label: 'Recruitment Forms', type: 'text', regex: /recruitment.*forms/i },
    ]
  },
];

const internalNoteFieldIds = new Set([
  'someApplicationsWeveDiscussedGoMuchDeeperHereaskingAboutClubChapterNgoLeadershipOrganizationSizeLevelAndImpact',
  'theseShouldNotSimplyBeAutofilledFromStaticProfileDataYourExtensionShouldHaveAnAnswerVaultForThem',
]);

export const applicationSchema = schemaSections
  .filter(section => section.id !== 'documents' && section.id !== 'legalConsent')
  .map(section => ({
    ...section,
    fields: section.fields.filter(field => !internalNoteFieldIds.has(field.id)),
  }));
